// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcKkzrDpH50nCUIB3UNcmbnpSbnUrh6AQ',
    appId: '1:656485263226:android:d6d3e92a1984ff1f2618c3',
    messagingSenderId: '656485263226',
    projectId: 'kitchen-sync-ad5a6',
    databaseURL: 'https://kitchen-sync-ad5a6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kitchen-sync-ad5a6.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4F0V93gsMfOsn54InoVrexJUeYXr4Ppg',
    appId: '1:656485263226:web:427e7295a6bd872a2618c3',
    messagingSenderId: '656485263226',
    projectId: 'kitchen-sync-ad5a6',
    authDomain: 'kitchen-sync-ad5a6.firebaseapp.com',
    databaseURL: 'https://kitchen-sync-ad5a6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kitchen-sync-ad5a6.firebasestorage.app',
    measurementId: 'G-Q6M3SE6YWK',
  );
}
